=== decentralized-identity/fuzzy-encryption/src/python/schema/input_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "Parameters for generating a secret with the Fuzzy Key Recovery system",
    "type": "object",
    "properties": {
        "setSize" : { 
            "type": "number",
            "description": "number of words in the original and recovery word list"
        },
        "corpusSize": { 
            "type": "number",
            "description": "size of the set of words to choose from"
        },
        "correctThreshold": {
            "type": "number",
            "description": "minimum number of correct words need to unlock keys\nless than or equal to setSize"
        },
        "randomBytes": {
            "type": "array",
            "description": "array of upper case hexadecimal strings encoding random bytes",
            "items": {
                "type": "string",
                "pattern": "^[0-9A-F]+$"
            }
        }
    },
    "additionalProperties": false,
    "required": [
        "setSize",
        "corpusSize",
        "correctThreshold"
    ]
}

=== decentralized-identity/fuzzy-encryption/src/python/schema/randinput.json
{
  "setSize": 9,
  "corpusSize": 7776,
  "correctThreshold": 6,
  "randomBytes": [
    "E4C57A65D4EA5129421C3E812734D8AF3458ED9DEED1DCFB2E6B470C1074192A",
    "1B6B5FC182E3D94132763622F4E0D8B2ECBB0154C97618771BAB9421EF3B1488",
    "6C1B1855F77171C536BCC29F514ACE8668FE60D24E50EA483C9F3205F581AF6A"
  ]
}
