=== decentralized-identity/fuzzy-encryption/src/python/schema/secret_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "Parameters for generating a secret with the Fuzzy Key Recovery system",
    "type": "object",
    "properties": {
        "setSize" : { 
            "type": "number",
            "description": "number of words in the original and recovery word list"
        },
        "corpusSize": { 
            "type": "number",
            "description": "size of the set of words to choose from"
        },
        "correctThreshold": {
            "type": "number",
            "description": "minimum number of correct words need to unlock keys\nless than or equal to setSize"
        },
        "prime": {
            "type": "number",
            "description": "a prime number in the range corpusSize < prime < 2 * corpusSize"
        },
        "extractor": {
            "type": "array",
            "description": "an array of numbers used in the key recovery process",
            "items": {
                "type": "number"
            }
        },
        "salt": { 
            "type": "string",
            "description": "salt to slow brute force attacks. Represents an array of bytes",
            "pattern": "^[0-9A-F]+$"
        },
        "sketch" : {
            "description": "an array of numbers used in the key recovery process",
            "items": {
                "type": "number"
            }
        },
        "hash" : {
            "type": "string",
            "description": "A 512-bit hash of the original words",
            "pattern": "^[0-9A-F]+$"
        }
    },
    "additionalProperties": false,
    "required": [
        "setSize",
        "corpusSize",
        "correctThreshold",
        "prime",
        "extractor",
        "salt",
        "sketch",
        "hash"
    ]
}

=== decentralized-identity/fuzzy-encryption/src/python/schema/secret.json
{
    "setSize": 9,
    "corpusSize": 7776,
    "correctThreshold": 6,
    "prime": 7789,
    "extractor": [ 67, 4012, 1657, 6910, 6730, 3480, 4674, 3710, 3586 ],
    "salt": "5EE4975616255C5CAED6C99F3635FE4F22D351F7199AE2FA5101B3595CFDC396",
    "sketch": [ 7092, 3290, 961, 6128, 870, 7744 ],
    "hash": "43F96FCEAB353FB488A00186BA7358CA5F2BF0EB36EE70EC64FCD3113827BB66735176DF56AF105C8F6D6BBB9F7068F23CD7D897CF2CD5D2D5CE266715897E6E"
}

=== decentralized-identity/fuzzy-encryption/src/python/fuzzyvault/secret.json
{
  "setSize": 12,
  "correctThreshold": 9,
  "corpusSize": 7776,
  "prime": 7789,
  "extractor": [
    3768,
    2965,
    7549,
    7745,
    4154,
    916,
    2614,
    1062,
    7201,
    1460,
    1837,
    7232
  ],
  "salt": "B072A87F6E71F2D128A535713C05B0B6189ABD16A66B09ADAE349E801C0886BF",
  "sketch": [
    967,
    5576,
    1719,
    6542,
    2717,
    7711
  ],
  "hash": "BC7008F9ECD92C33914D14533D3BDB7597F751F632306F35F3DD800BE8AAFCA5C0EB022597FCC50FE84F73439F4CA0963718D3006517A4783224A3B14E4DC548"
}
